swagger: '2.0'
info:
  title: Workers API
  description: API description in Markdown.
  version: 1.0.0
basePath: /api
paths:
  /worker:
    get:
      operationId: doc.worker.read
      tags:
        - Worker
      summary: Summary
      description: Read the list of workers
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                timestamp:
                  type: string
  '/worker/{id}':
    get:
      operationId: doc.worker.read_by_id
      tags:
        - Worker
      summary: Summary
      description: Get one worker by id
      parameters:
        - name: id
          in: path
          required: true
          description: Identificación del worker
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              first_name:
                type: string
              last_name:
                type: string
              timestamp:
                type: string
        '404':
          description: Id not found
          schema:
            type: object
            properties:
              message:
                type: string
        default:
          description: Error inesperado.
          schema:
            $ref: '#/definitions/Error'

definitions:
  Error:
    type: object
    properties:
      code:
        type: integer
      message:
        type: string